### ISSUE TITLE
Version Number 0.0.0

### ISSUE THREAD

**Issue by pburtchaell** [hughsk/gulp-duration#1]
I was just checking in to see if you intended for the version number to be 0.0.0. This could cause issues down the line with npm.

**Comment by hughsk** [comment]
Hi! What sort of issues?

**Comment by pburtchaell** [comment]
Nothing major, just possible confusion over what version is current and whether or not an update is required.

**Comment by hughsk** [comment]
Sorry, I'm not 100% sure what you mean? gulp-duration is at 0.0.0 because it hasn't needed any updates yet – I'm pretty vigilant about versioning and will be sure to increment the version in the future if it does though :)

**Comment by pburtchaell** [comment]
Gotcha! I suppose my question was directed at why the version isn't 0.1.0, but I see you publish the first version at 0.0.0. 

Closing.

**Comment by hughsk** [comment]
Cool, no worries :)
